# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b73ce3558c74c1fc4a530e4ff495a1e84905878437ebf1effa8c322f904fef44d877d430fc8d935373180beca953a29201da13349ea5d8cbf9153da64566b9c

test:
  secret_key_base: 50a0d672e1f66c87eba219b66d4884878f1b81ed374db02b2661ac1d6564ac0174551098d6afe255c7574d6a3a047dbadd88b91145098cd7c7ef7da998dd2d9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
